// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: prefer_single_quotes

// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

import 'package:flutterpluginwangfei/json/modle/image_bean_entity.dart';

import '../modle/image_bean_entity_helper.dart';

class JsonConvert<T> {
  T fromJson(Map<String, dynamic> json) {
    return _getFromJson<T>(runtimeType, this, json);
  }

  Map<String, dynamic> toJson() {
    return _getToJson<T>(runtimeType, this);
  }

  static _getFromJson<T>(Type type, data, json) {
    switch (type) {
      case ImageBeanEntity:
        return imageBeanEntityFromJson(data as ImageBeanEntity, json) as T;
      case ImageBeanImageList:
        return imageBeanImageListFromJson(data as ImageBeanImageList, json)
            as T;
    }
    return data as T;
  }

  static _getToJson<T>(Type type, data) {
    switch (type) {
      case ImageBeanEntity:
        return imageBeanEntityToJson(data as ImageBeanEntity);
      case ImageBeanImageList:
        return imageBeanImageListToJson(data as ImageBeanImageList);
    }
    return data as T;
  }

  //Go back to a single instance by type
  static _fromJsonSingle(String type, json) {
    switch (type) {
      case 'ImageBeanEntity':
        return ImageBeanEntity().fromJson(json);
      case 'ImageBeanImageList':
        return ImageBeanImageList().fromJson(json);
    }
    return null;
  }

  //empty list is returned by type
  static _getListFromType(String type) {
    switch (type) {
      case 'ImageBeanEntity':
        return List<ImageBeanEntity>();
      case 'ImageBeanImageList':
        return List<ImageBeanImageList>();
    }
    return null;
  }

  static M fromJsonAsT<M>(json) {
    String type = M.toString();
    if (json is List && type.contains("List<")) {
      String itemType = type.substring(5, type.length - 1);
      List tempList = _getListFromType(itemType);
      json.forEach((itemJson) {
        tempList
            .add(_fromJsonSingle(type.substring(5, type.length - 1), itemJson));
      });
      return tempList as M;
    } else {
      return _fromJsonSingle(M.toString(), json) as M;
    }
  }
}
